version: '3.8'
services:

  ##########################################################################
  #dicovery server
  ##########################################################################
  registry-discovery:
    container_name: id-eureka
    image: mpraviap/microservice-docker-eurekaserver:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    environment:
      - JAVA_OPTS=
        -Xms256M
        -Xmx256M

  ##########################################################################
  #configuration service
  ##########################################################################
  configuration:
    container_name: id-config
    image: mpraviap/microservice-docker-configserver:0.0.1-SNAPSHOT
    volumes:
      #this it use because we are using a local github repository /host/path:/container/path use ./ for relative path
      - ./config-server-repo:/tmp/config-server-repo
      #All projets will have a variable value  DEUREKA_SERVER this tell where find a registry-discovery server
    environment:
      - JAVA_OPTS=
        -Xms256M
        -Xmx256M
        -DEUREKA_SERVER=http://registry-discovery:8761/eureka/
        -DLOCAL_REPOSITORY=/tmp/config-server-repo
      #-Dspring.cloud.config.server.native.searchLocations=/var/config-data
    depends_on:
      - registry-discovery
    ports:
      - 8888:8888

  ##########################################################################
  #administration service
  ##########################################################################
  administration:
    container_name: id-admin
    image: mpraviap/microservice-docker-adminserver:0.0.1-SNAPSHOT
    #All projets will have a variable value  DEUREKA_SERVER this tell where find a registry-discovery server
    environment:
      - JAVA_OPTS=
        -Xms256M
        -Xmx256M
        -DEUREKA_SERVER=http://registry-discovery:8761/eureka/
      #-Dspring.cloud.config.server.native.searchLocations=/var/config-data
    depends_on:
      - registry-discovery
    ports:
      - 8762:8762


  ##########################################################################
  #apigateway service
  ##########################################################################
  apigateway:
    container_name: id-apigateway
    image: mpraviap/microservice-docker-apigateway:0.0.1-SNAPSHOT
    #All projets will have a variable value  DEUREKA_SERVER this tell where find a registry-discovery server
    environment:
      - JAVA_OPTS=
        -Xms256M
        -Xmx256M
        -DEUREKA_SERVER=http://registry-discovery:8761/eureka/
      #-Dspring.cloud.config.server.native.searchLocations=/var/config-data
    depends_on:
      - registry-discovery
    ports:
      - 8080:8080



  ##########################################################################
  #keycloack service
  ##########################################################################
  keycloack:
    container_name: keycloakAdapter
    image: mpraviap/microservice-docker-keycloack-adapter:0.0.1-SNAPSHOT
    #All projets will have a variable value  DEUREKA_SERVER this tell where find a registry-discovery server
    environment:
      - JAVA_OPTS=
        -Xms256M
        -Xmx256M
        -DEUREKA_SERVER=http://registry-discovery:8761/eureka/
        -DKEYCLOACK_SERVER=http://keycloack_server:8080/auth/realms/
        -DKEYCLOACK_REAL_ID=3AJd4nppsHhA1GRr6jBgM2hvH6LhG9_XiDApujdy3NI
      #-Dspring.cloud.config.server.native.searchLocations=/var/config-data
    depends_on:
      - registry-discovery
    ports:
      - 8088:8088

  ##########################################################################
  #product service
  ##########################################################################
  product-catalog:
    container_name: bd-product-catalog
    image: mpraviap/microservice-docker-products:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -Xms256M
        -Xmx256M
        -DEUREKA_SERVER=http://registry-discovery:8761/eureka/
        -Dspring.profiles.active=production
    depends_on:
      - registry-discovery
      - configuration
    ports:
      - 8083:8083

  ##########################################################################
  #user service
  ##########################################################################
  customer:
    container_name: bd-user
    image: mpraviap/microservice-docker-customer:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -Xms256M
        -Xmx256M
        -DEUREKA_SERVER=http://registry-discovery:8761/eureka/
        -Dspring.profiles.active=production
    depends_on:
      - registry-discovery
      - configuration

  ##########################################################################
  #transaction service
  ##########################################################################
  transactions:
    container_name: bd-sale
    image: mpraviap/microservice-docker-transactions:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -Xms256M
        -Xmx256M
        -DEUREKA_SERVER=http://registry-discovery:8761/eureka/
        -Dspring.profiles.active=production
    depends_on:
      - registry-discovery
      - configuration


  ##########################################################################
  #keycloack Server
  ##########################################################################
  keycloack_server:
    container_name: id-keycloackServer
    image: jboss/keycloak
    restart: always
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: H2
    ports:
      - 8091:8080

  ##########################################################################
  #mongoDB Server
  ##########################################################################
  mongodb_server:
    container_name: id-mongodbServer
    image: mongodb/mongodb-community-server
    restart: always
    ports:
      - 27017:27017

